TELEGRAM_API_KEY = ""
IMAGE_CHANNEL_ID = ""
TEXT_CHANNEL_ID = ""
LOGGER_CHAT_ID = ""
SHARE_TIME_HOUR = 9
SHARE_TIME_MINUTE = 15
UPDATE_DB_TIME_HOUR = 15
UPDATE_DB_TIME_MINUTE = 0
WEBHOOK_CONNECTED = false
PORT = "8080"
WEBHOOK_URL = ""
BACKGROUND_COLORS = ["#C9D6DF", "#F8F3D4", "#FFE2E2", "#E7D4B5", "#AEDEFC", "#EAFFD0", "#FFD3B4", "#BAC7A7", "#95E1D3", "#FCE38A", "#FFB4B4"]
