TELEGRAM_API_KEY = ""
IMAGE_CHANNEL_ID = 0
TEXT_CHANNEL_ID = 0
LOGGER_CHAT_ID = 0
SHARE_TIME_HOUR = 9
SHARE_TIME_MINUTE = 15
UPDATE_DB_TIME_HOUR = 15
UPDATE_DB_TIME_MINUTE = 0
WEBHOOK_CONNECTED = false
PORT = "8080"
WEBHOOK_URL = ""
BACKGROUND_COLORS = ["#C9D6DF", "#F8F3D4", "#FFE2E2", "#E7D4B5", "#AEDEFC", "#EAFFD0", "#FFD3B4", "#BAC7A7", "#95E1D3", "#FCE38A", "#FFB4B4"]
SMTP_HOST = ""
SMTP_PORT = 587
SMTP_USERNAME = ""
SMTP_PASSWORD = ""
MAILING_LIST_ADDRESS = ""
